version: '3.8'

services:
  netiv3:
    image: netiv3:latest 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: netiv3_app
    restart: unless-stopped
    ports:
      - "5004:5004"
    
    environment:
      - SECRET_KEY=YOUR_PRODUCTION_SECRET_KEY_HERE
      - GEMINI_API_KEY=YOUR_GEMINI_API_KEY_HERE
      - MSF_RPC_HOST=10.28.14.20 
      - MSF_RPC_PORT=55553
      - MSF_RPC_PASSWORD=netiv3pass
