version: '3.8'

services:
  # Layanan utama netiV3
  netiv3:
    # 📌 SOLUSI 1: Mendefinisikan nama image secara eksplisit agar Portainer tidak bingung
    image: netiv3:latest 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: netiv3_app
    restart: unless-stopped
    ports:
      - "5004:5004"
    
    # 📌 Konfigurasi environment (Isi ini di Portainer Environment Variables)
    environment:
      # Ganti nilai di bawah ini di Portainer untuk keamanan
      - SECRET_KEY=YOUR_PRODUCTION_SECRET_KEY_HERE
      - GEMINI_API_KEY=YOUR_GEMINI_API_KEY_HERE
      # Pastikan ini sesuai dengan konfigurasi Metasploit Anda
      - MSF_RPC_HOST=10.28.14.20 # Ganti jika Metasploit berjalan di server terpisah
      - MSF_RPC_PORT=55553
      - MSF_RPC_PASSWORD=netiv3pass
      
  # Layanan Metasploit RPC (Opsional, jika Anda ingin MSF berjalan di container terpisah)
  # Jika Metasploit berjalan di luar Docker, hapus bagian ini.
  # msfrpcd:
  #   image: metasploitframework/metasploit-framework:latest
  #   container_name: msf_rpc
  #   restart: unless-stopped
  #   ports:
  #     - "55553:55553"
  #   command: msfrpcd -P netiv3pass -p 55553 -n -a 0.0.0.0
